import type { CaptionStyle } from '../models';

// 12 premium kinetic caption styles, CapCut / KineCut inspired.
// Each style is fully specified: typography, colors, background treatment,
// optional stroke / glow, and its signature animation (see KineticPreview).
export const CAPTION_STYLES: CaptionStyle[] = [
  {
    id: 'karaoke-gold',
    name: 'Karaoke Gold',
    tagline: 'Classic sing-along glow',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 28,
    fontWeight: '800',
    textColor: '#FFFFFF',
    highlightColor: '#FFC531',
    background: { type: 'pill', color: 'rgba(0,0,0,0.55)', radius: 12, padding: 10 },
    glow: { color: '#FFC531', radius: 18 },
    animation: 'karaoke',
  },
  {
    id: 'pop-punch',
    name: 'Pop Punch',
    tagline: 'Bold comic-book pop',
    fontFamily: 'Archivo_900Black',
    fontSize: 34,
    fontWeight: '900',
    textColor: '#FFFFFF',
    highlightColor: '#E8FF47',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    stroke: { color: '#000000', width: 3 },
    animation: 'pop',
    uppercase: true,
  },
  {
    id: 'typewriter-mono',
    name: 'Typewriter Mono',
    tagline: 'Retro terminal typing',
    fontFamily: 'SpaceMono_700Bold',
    fontSize: 24,
    fontWeight: '700',
    textColor: '#4ADE80',
    highlightColor: '#BBF7D0',
    background: { type: 'box', color: '#050805', radius: 4, padding: 12 },
    animation: 'typewriter',
  },
  {
    id: 'bounce-fun',
    name: 'Bounce Fun',
    tagline: 'Playful bouncy words',
    fontFamily: 'Poppins_800ExtraBold',
    fontSize: 30,
    fontWeight: '800',
    textColor: '#FFFFFF',
    highlightColor: '#FF7AC6',
    background: { type: 'pill', color: '#8B5CF6', radius: 999, padding: 10 },
    animation: 'bounce',
  },
  {
    id: 'neon-glow',
    name: 'Neon Glow',
    tagline: 'Electric night-club neon',
    fontFamily: 'BebasNeue_400Regular',
    fontSize: 42,
    fontWeight: '400',
    textColor: '#E0FBFF',
    highlightColor: '#22D3EE',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    glow: { color: '#22D3EE', radius: 26 },
    animation: 'glow-pulse',
    uppercase: true,
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    tagline: 'Understated pro subtitles',
    fontFamily: 'Inter_600SemiBold',
    fontSize: 20,
    fontWeight: '600',
    textColor: '#F3F4F6',
    highlightColor: '#FFFFFF',
    background: { type: 'pill', color: 'rgba(0,0,0,0.45)', radius: 8, padding: 8 },
    animation: 'minimal',
  },
  {
    id: 'impact-bold',
    name: 'Impact Bold',
    tagline: 'Meme-style heavy hitter',
    fontFamily: 'Anton_400Regular',
    fontSize: 46,
    fontWeight: '400',
    textColor: '#FFFFFF',
    highlightColor: '#FFD60A',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    stroke: { color: '#000000', width: 4 },
    animation: 'scale-punch',
    uppercase: true,
  },
  {
    id: 'outline-pro',
    name: 'Outline Pro',
    tagline: 'Hollow outline that fills',
    fontFamily: 'Archivo_900Black',
    fontSize: 36,
    fontWeight: '900',
    textColor: '#FFFFFF',
    highlightColor: '#E8FF47',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    stroke: { color: '#FFFFFF', width: 2 },
    animation: 'outline',
    uppercase: true,
  },
  {
    id: 'gradient-hype',
    name: 'Gradient Hype',
    tagline: 'Streetwear hype energy',
    fontFamily: 'Poppins_800ExtraBold',
    fontSize: 30,
    fontWeight: '800',
    textColor: '#0B0B10',
    highlightColor: '#0B0B10',
    background: { type: 'box', color: '#E8FF47', radius: 6, padding: 10 },
    animation: 'slide-in',
    uppercase: true,
  },
  {
    id: 'capcut-highlight',
    name: 'CapCut Highlight',
    tagline: 'Auto-caption word pill',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 26,
    fontWeight: '800',
    textColor: '#FFFFFF',
    highlightColor: '#E8FF47',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    animation: 'word-highlight',
    uppercase: true,
  },
  {
    id: 'fade-up-elegant',
    name: 'Fade Up Elegant',
    tagline: 'Cinematic lower-third',
    fontFamily: 'Inter_400Regular',
    fontSize: 22,
    fontWeight: '400',
    textColor: '#F5F0E8',
    highlightColor: '#FFC531',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    animation: 'fade-up',
  },
  {
    id: 'classic-stroke',
    name: 'Classic Stroke',
    tagline: 'Timeless TV subtitle',
    fontFamily: 'Inter_800ExtraBold',
    fontSize: 24,
    fontWeight: '800',
    textColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    background: { type: 'none', color: 'transparent', radius: 0, padding: 0 },
    stroke: { color: '#000000', width: 2 },
    animation: 'minimal',
  },
];

export function getStyleById(id: string): CaptionStyle {
  return CAPTION_STYLES.find((s) => s.id === id) ?? CAPTION_STYLES[0];
}
